import { useMemo } from "react";
import { toast } from "react-toastify";
import {
  useAdminGenerateUserCustodialWalletsMutation,
  useAdminUserCustodialWalletsQuery,
} from "../../../../queries/crypto.querries";
import type { CustodialWalletResponsePayload, SearchSupportedCryptoData } from "../../../../types/response.payload.types";

interface CustodialWalletsSectionProps {
  userId: string | undefined;
  supportedCryptos: Array<SearchSupportedCryptoData> | null | undefined;
}

// Copy text to clipboard with toast feedback.
const copyToClipboard = async (text: string) => {
  try {
    await navigator.clipboard.writeText(text);
    toast.success("Copied to clipboard.");
  } catch {
    toast.error("Failed to copy.");
  }
};

// Render a compact skeleton card.
const WalletSkeleton = () => {
  return (
    <div className="bg-white rounded-lg p-6 mb-6">
      <div className="flex items-center justify-between mb-6">
        <div className="h-6 w-48 bg-[#F2F4F7] rounded animate-pulse" />
        <div className="h-10 w-40 bg-[#F2F4F7] rounded-full animate-pulse" />
      </div>
      <div className="space-y-3">
        {Array.from({ length: 3 }).map((_, idx) => (
          <div key={idx} className="p-4 border rounded-lg">
            <div className="flex items-center justify-between gap-3">
              <div className="min-w-0 flex-1">
                <div className="h-4 w-44 bg-[#F2F4F7] rounded animate-pulse" />
                <div className="h-3 w-72 bg-[#F2F4F7] rounded animate-pulse mt-2" />
              </div>
              <div className="h-9 w-20 bg-[#F2F4F7] rounded-full animate-pulse" />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

// Sort wallets by network then address for stable UI.
const sortWallets = (wallets: CustodialWalletResponsePayload[]) => {
  return [...wallets].sort((a, b) => {
    const netCmp = a.network.localeCompare(b.network);
    if (netCmp !== 0) return netCmp;
    const envCmp = a.blockchainEnvironment.localeCompare(b.blockchainEnvironment);
    if (envCmp !== 0) return envCmp;
    return a.walletAddress.localeCompare(b.walletAddress);
  });
};

const getEnvironmentMeta = (environment: CustodialWalletResponsePayload["blockchainEnvironment"]) => {
  if (environment === "mainnet") {
    return {
      label: "Mainnet",
      badgeClass: "bg-emerald-50 text-emerald-700 border-emerald-200",
      cardClass: "border-[#DDE0FF] bg-white",
    };
  }

  return {
    label: "Testnet",
    badgeClass: "bg-amber-50 text-amber-700 border-amber-200",
    cardClass: "border-amber-200 bg-amber-50/60",
  };
};

const CustodialWalletsSection = ({ userId, supportedCryptos }: CustodialWalletsSectionProps) => {
  const { data: wallets, isLoading } = useAdminUserCustodialWalletsQuery(userId);
  const generateMutation = useAdminGenerateUserCustodialWalletsMutation(userId);

  const cryptoById = useMemo(() => {
    const entries = (supportedCryptos ?? []).map((c) => [c.id, c] as const);
    return new Map(entries);
  }, [supportedCryptos]);

  const sortedWallets = useMemo(() => (wallets ? sortWallets(wallets) : []), [wallets]);

  if (isLoading) return <WalletSkeleton />;

  return (
    <div className="bg-white rounded-lg p-6 mb-6">
      <div className="flex items-start sm:items-center justify-between gap-3 mb-6">
        <div>
          <h2 className="text-xl font-semibold text-[#0E0F0C]">Custodial Wallets</h2>
          <p className="text-sm text-[#667085] mt-1">
            These are the user’s unique deposit addresses (generated by the platform).
          </p>
        </div>

        <button
          onClick={() => generateMutation.mutate()}
          disabled={!userId || generateMutation.isPending}
          className="px-4 py-2 rounded-full bg-[#03034D] text-white text-sm hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
        >
          {generateMutation.isPending ? "Generating..." : "Generate missing wallets"}
        </button>
      </div>

      {!sortedWallets || sortedWallets.length === 0 ? (
        <div className="text-center py-8 text-[#667085]">
          No custodial wallets yet. Click “Generate missing wallets”.
        </div>
      ) : (
        <div className="space-y-3">
          {sortedWallets.map((wallet) => {
            const crypto = cryptoById.get(wallet.cryptocurrencyId);
            const title = crypto ? `${crypto.name} (${crypto.symbol})` : "Crypto";
            const env = getEnvironmentMeta(wallet.blockchainEnvironment);

            return (
              <div key={wallet.id} className={`p-4 border rounded-lg ${env.cardClass}`}>
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                  <div className="min-w-0">
                    <div className="flex items-center gap-2">
                      <div className="font-medium text-[#0E0F0C] truncate">{title}</div>
                      <span className="text-[12px] px-2 py-1 rounded-full bg-[#F2F4F7] text-[#344054]">
                        {wallet.network}
                      </span>
                      <span className={`text-[12px] px-2 py-1 rounded-full border ${env.badgeClass}`}>
                        {env.label}
                      </span>
                      {!wallet.isActive ? (
                        <span className="text-[12px] px-2 py-1 rounded-full bg-[#FCE8E8] text-[#B42318]">
                          Inactive
                        </span>
                      ) : null}
                    </div>
                    <div className="mt-2 font-mono text-[13px] text-[#475467] break-all">
                      {wallet.walletAddress}
                    </div>
                  </div>

                  <div className="flex items-center gap-2 justify-end">
                    <button
                      onClick={() => copyToClipboard(wallet.walletAddress)}
                      className="px-3 py-2 rounded-full bg-[#EAE9FC] text-[#3B37A1] text-sm font-medium cursor-pointer hover:opacity-80"
                    >
                      Copy
                    </button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default CustodialWalletsSection;
