export type DisputeResolution = "APPROVED" | "REJECTED" | "REFUNDED" | "PARTIALLY_REFUNDED" | "TRANSACTION_CORRECTED" | "NO_ACTION_REQUIRED" | "ESCALATED_TO_MANAGEMENT"

export type DisputeStatus = 'OPEN' | 'UNDER_REVIEW' | 'AWAITING_EVIDENCE' | 'AWAITING_USER_RESPONSE' | 'AWAITING_ADMIN_RESPONSE' | 'ESCALATED' | 'RESOLVED' | 'REJECTED' | 'CLOSED'

export type DisputePriority = 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT'