/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTestimonialsRouteImport } from './routes/dashboard/testimonials'
import { Route as DashboardSupportedCurrenciesRouteImport } from './routes/dashboard/supported-currencies'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardManageFiatRouteImport } from './routes/dashboard/manage-fiat'
import { Route as DashboardManageAdminsRouteImport } from './routes/dashboard/manage-admins'
import { Route as DashboardKycTierLimitsRouteImport } from './routes/dashboard/kyc-tier-limits'
import { Route as DashboardAuditTrailsRouteImport } from './routes/dashboard/audit-trails'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardTreasuryIndexRouteImport } from './routes/dashboard/treasury/index'
import { Route as DashboardTransactionsIndexRouteImport } from './routes/dashboard/transactions/index'
import { Route as DashboardKycSessionsIndexRouteImport } from './routes/dashboard/kyc-sessions/index'
import { Route as DashboardDisputesIndexRouteImport } from './routes/dashboard/disputes/index'
import { Route as DashboardCoinManagementIndexRouteImport } from './routes/dashboard/coin-management/index'
import { Route as DashboardUserUserIdRouteImport } from './routes/dashboard/user/$userId'
import { Route as DashboardTreasuryWalletsRouteImport } from './routes/dashboard/treasury/wallets'
import { Route as DashboardTreasurySweepIdRouteImport } from './routes/dashboard/treasury/$sweepId'
import { Route as DashboardTransactionIdRouteImport } from './routes/dashboard/transaction/$id'
import { Route as DashboardManageAdminsAdminIdRouteImport } from './routes/dashboard/manage-admins/$adminId'
import { Route as DashboardKycSessionIdRouteImport } from './routes/dashboard/kyc-session/$id'
import { Route as DashboardDisputeIdRouteImport } from './routes/dashboard/dispute/$id'
import { Route as DashboardCustodialWalletWalletAddressRouteImport } from './routes/dashboard/custodial-wallet/$walletAddress'
import { Route as DashboardCoinManagementAddCoinRouteImport } from './routes/dashboard/coin-management/add-coin'
import { Route as DashboardCoinManagementCoinIdRouteImport } from './routes/dashboard/coin-management/$coinId'
import { Route as DashboardUsersTransactionHistoryUserIdRouteImport } from './routes/dashboard/users/transaction-history/$userId'
import { Route as DashboardDisputesEditIdRouteImport } from './routes/dashboard/disputes/edit/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTestimonialsRoute = DashboardTestimonialsRouteImport.update({
  id: '/dashboard/testimonials',
  path: '/dashboard/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupportedCurrenciesRoute =
  DashboardSupportedCurrenciesRouteImport.update({
    id: '/dashboard/supported-currencies',
    path: '/dashboard/supported-currencies',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManageFiatRoute = DashboardManageFiatRouteImport.update({
  id: '/dashboard/manage-fiat',
  path: '/dashboard/manage-fiat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManageAdminsRoute = DashboardManageAdminsRouteImport.update({
  id: '/dashboard/manage-admins',
  path: '/dashboard/manage-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardKycTierLimitsRoute = DashboardKycTierLimitsRouteImport.update({
  id: '/dashboard/kyc-tier-limits',
  path: '/dashboard/kyc-tier-limits',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuditTrailsRoute = DashboardAuditTrailsRouteImport.update({
  id: '/dashboard/audit-trails',
  path: '/dashboard/audit-trails',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/dashboard/users/',
  path: '/dashboard/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTreasuryIndexRoute = DashboardTreasuryIndexRouteImport.update({
  id: '/dashboard/treasury/',
  path: '/dashboard/treasury/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTransactionsIndexRoute =
  DashboardTransactionsIndexRouteImport.update({
    id: '/dashboard/transactions/',
    path: '/dashboard/transactions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardKycSessionsIndexRoute =
  DashboardKycSessionsIndexRouteImport.update({
    id: '/dashboard/kyc-sessions/',
    path: '/dashboard/kyc-sessions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardDisputesIndexRoute = DashboardDisputesIndexRouteImport.update({
  id: '/dashboard/disputes/',
  path: '/dashboard/disputes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoinManagementIndexRoute =
  DashboardCoinManagementIndexRouteImport.update({
    id: '/dashboard/coin-management/',
    path: '/dashboard/coin-management/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardUserUserIdRoute = DashboardUserUserIdRouteImport.update({
  id: '/dashboard/user/$userId',
  path: '/dashboard/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTreasuryWalletsRoute =
  DashboardTreasuryWalletsRouteImport.update({
    id: '/dashboard/treasury/wallets',
    path: '/dashboard/treasury/wallets',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTreasurySweepIdRoute =
  DashboardTreasurySweepIdRouteImport.update({
    id: '/dashboard/treasury/$sweepId',
    path: '/dashboard/treasury/$sweepId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTransactionIdRoute = DashboardTransactionIdRouteImport.update({
  id: '/dashboard/transaction/$id',
  path: '/dashboard/transaction/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManageAdminsAdminIdRoute =
  DashboardManageAdminsAdminIdRouteImport.update({
    id: '/$adminId',
    path: '/$adminId',
    getParentRoute: () => DashboardManageAdminsRoute,
  } as any)
const DashboardKycSessionIdRoute = DashboardKycSessionIdRouteImport.update({
  id: '/dashboard/kyc-session/$id',
  path: '/dashboard/kyc-session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDisputeIdRoute = DashboardDisputeIdRouteImport.update({
  id: '/dashboard/dispute/$id',
  path: '/dashboard/dispute/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCustodialWalletWalletAddressRoute =
  DashboardCustodialWalletWalletAddressRouteImport.update({
    id: '/dashboard/custodial-wallet/$walletAddress',
    path: '/dashboard/custodial-wallet/$walletAddress',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCoinManagementAddCoinRoute =
  DashboardCoinManagementAddCoinRouteImport.update({
    id: '/dashboard/coin-management/add-coin',
    path: '/dashboard/coin-management/add-coin',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCoinManagementCoinIdRoute =
  DashboardCoinManagementCoinIdRouteImport.update({
    id: '/dashboard/coin-management/$coinId',
    path: '/dashboard/coin-management/$coinId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardUsersTransactionHistoryUserIdRoute =
  DashboardUsersTransactionHistoryUserIdRouteImport.update({
    id: '/dashboard/users/transaction-history/$userId',
    path: '/dashboard/users/transaction-history/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardDisputesEditIdRoute = DashboardDisputesEditIdRouteImport.update({
  id: '/dashboard/disputes/edit/$id',
  path: '/dashboard/disputes/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/audit-trails': typeof DashboardAuditTrailsRoute
  '/dashboard/kyc-tier-limits': typeof DashboardKycTierLimitsRoute
  '/dashboard/manage-admins': typeof DashboardManageAdminsRouteWithChildren
  '/dashboard/manage-fiat': typeof DashboardManageFiatRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/supported-currencies': typeof DashboardSupportedCurrenciesRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/coin-management/$coinId': typeof DashboardCoinManagementCoinIdRoute
  '/dashboard/coin-management/add-coin': typeof DashboardCoinManagementAddCoinRoute
  '/dashboard/custodial-wallet/$walletAddress': typeof DashboardCustodialWalletWalletAddressRoute
  '/dashboard/dispute/$id': typeof DashboardDisputeIdRoute
  '/dashboard/kyc-session/$id': typeof DashboardKycSessionIdRoute
  '/dashboard/manage-admins/$adminId': typeof DashboardManageAdminsAdminIdRoute
  '/dashboard/transaction/$id': typeof DashboardTransactionIdRoute
  '/dashboard/treasury/$sweepId': typeof DashboardTreasurySweepIdRoute
  '/dashboard/treasury/wallets': typeof DashboardTreasuryWalletsRoute
  '/dashboard/user/$userId': typeof DashboardUserUserIdRoute
  '/dashboard/coin-management/': typeof DashboardCoinManagementIndexRoute
  '/dashboard/disputes/': typeof DashboardDisputesIndexRoute
  '/dashboard/kyc-sessions/': typeof DashboardKycSessionsIndexRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/dashboard/treasury/': typeof DashboardTreasuryIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/disputes/edit/$id': typeof DashboardDisputesEditIdRoute
  '/dashboard/users/transaction-history/$userId': typeof DashboardUsersTransactionHistoryUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/audit-trails': typeof DashboardAuditTrailsRoute
  '/dashboard/kyc-tier-limits': typeof DashboardKycTierLimitsRoute
  '/dashboard/manage-admins': typeof DashboardManageAdminsRouteWithChildren
  '/dashboard/manage-fiat': typeof DashboardManageFiatRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/supported-currencies': typeof DashboardSupportedCurrenciesRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/coin-management/$coinId': typeof DashboardCoinManagementCoinIdRoute
  '/dashboard/coin-management/add-coin': typeof DashboardCoinManagementAddCoinRoute
  '/dashboard/custodial-wallet/$walletAddress': typeof DashboardCustodialWalletWalletAddressRoute
  '/dashboard/dispute/$id': typeof DashboardDisputeIdRoute
  '/dashboard/kyc-session/$id': typeof DashboardKycSessionIdRoute
  '/dashboard/manage-admins/$adminId': typeof DashboardManageAdminsAdminIdRoute
  '/dashboard/transaction/$id': typeof DashboardTransactionIdRoute
  '/dashboard/treasury/$sweepId': typeof DashboardTreasurySweepIdRoute
  '/dashboard/treasury/wallets': typeof DashboardTreasuryWalletsRoute
  '/dashboard/user/$userId': typeof DashboardUserUserIdRoute
  '/dashboard/coin-management': typeof DashboardCoinManagementIndexRoute
  '/dashboard/disputes': typeof DashboardDisputesIndexRoute
  '/dashboard/kyc-sessions': typeof DashboardKycSessionsIndexRoute
  '/dashboard/transactions': typeof DashboardTransactionsIndexRoute
  '/dashboard/treasury': typeof DashboardTreasuryIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/disputes/edit/$id': typeof DashboardDisputesEditIdRoute
  '/dashboard/users/transaction-history/$userId': typeof DashboardUsersTransactionHistoryUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/audit-trails': typeof DashboardAuditTrailsRoute
  '/dashboard/kyc-tier-limits': typeof DashboardKycTierLimitsRoute
  '/dashboard/manage-admins': typeof DashboardManageAdminsRouteWithChildren
  '/dashboard/manage-fiat': typeof DashboardManageFiatRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/supported-currencies': typeof DashboardSupportedCurrenciesRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/coin-management/$coinId': typeof DashboardCoinManagementCoinIdRoute
  '/dashboard/coin-management/add-coin': typeof DashboardCoinManagementAddCoinRoute
  '/dashboard/custodial-wallet/$walletAddress': typeof DashboardCustodialWalletWalletAddressRoute
  '/dashboard/dispute/$id': typeof DashboardDisputeIdRoute
  '/dashboard/kyc-session/$id': typeof DashboardKycSessionIdRoute
  '/dashboard/manage-admins/$adminId': typeof DashboardManageAdminsAdminIdRoute
  '/dashboard/transaction/$id': typeof DashboardTransactionIdRoute
  '/dashboard/treasury/$sweepId': typeof DashboardTreasurySweepIdRoute
  '/dashboard/treasury/wallets': typeof DashboardTreasuryWalletsRoute
  '/dashboard/user/$userId': typeof DashboardUserUserIdRoute
  '/dashboard/coin-management/': typeof DashboardCoinManagementIndexRoute
  '/dashboard/disputes/': typeof DashboardDisputesIndexRoute
  '/dashboard/kyc-sessions/': typeof DashboardKycSessionsIndexRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/dashboard/treasury/': typeof DashboardTreasuryIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/disputes/edit/$id': typeof DashboardDisputesEditIdRoute
  '/dashboard/users/transaction-history/$userId': typeof DashboardUsersTransactionHistoryUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/dashboard/audit-trails'
    | '/dashboard/kyc-tier-limits'
    | '/dashboard/manage-admins'
    | '/dashboard/manage-fiat'
    | '/dashboard/notifications'
    | '/dashboard/supported-currencies'
    | '/dashboard/testimonials'
    | '/dashboard/'
    | '/dashboard/coin-management/$coinId'
    | '/dashboard/coin-management/add-coin'
    | '/dashboard/custodial-wallet/$walletAddress'
    | '/dashboard/dispute/$id'
    | '/dashboard/kyc-session/$id'
    | '/dashboard/manage-admins/$adminId'
    | '/dashboard/transaction/$id'
    | '/dashboard/treasury/$sweepId'
    | '/dashboard/treasury/wallets'
    | '/dashboard/user/$userId'
    | '/dashboard/coin-management/'
    | '/dashboard/disputes/'
    | '/dashboard/kyc-sessions/'
    | '/dashboard/transactions/'
    | '/dashboard/treasury/'
    | '/dashboard/users/'
    | '/dashboard/disputes/edit/$id'
    | '/dashboard/users/transaction-history/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/dashboard/audit-trails'
    | '/dashboard/kyc-tier-limits'
    | '/dashboard/manage-admins'
    | '/dashboard/manage-fiat'
    | '/dashboard/notifications'
    | '/dashboard/supported-currencies'
    | '/dashboard/testimonials'
    | '/dashboard'
    | '/dashboard/coin-management/$coinId'
    | '/dashboard/coin-management/add-coin'
    | '/dashboard/custodial-wallet/$walletAddress'
    | '/dashboard/dispute/$id'
    | '/dashboard/kyc-session/$id'
    | '/dashboard/manage-admins/$adminId'
    | '/dashboard/transaction/$id'
    | '/dashboard/treasury/$sweepId'
    | '/dashboard/treasury/wallets'
    | '/dashboard/user/$userId'
    | '/dashboard/coin-management'
    | '/dashboard/disputes'
    | '/dashboard/kyc-sessions'
    | '/dashboard/transactions'
    | '/dashboard/treasury'
    | '/dashboard/users'
    | '/dashboard/disputes/edit/$id'
    | '/dashboard/users/transaction-history/$userId'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/dashboard/audit-trails'
    | '/dashboard/kyc-tier-limits'
    | '/dashboard/manage-admins'
    | '/dashboard/manage-fiat'
    | '/dashboard/notifications'
    | '/dashboard/supported-currencies'
    | '/dashboard/testimonials'
    | '/dashboard/'
    | '/dashboard/coin-management/$coinId'
    | '/dashboard/coin-management/add-coin'
    | '/dashboard/custodial-wallet/$walletAddress'
    | '/dashboard/dispute/$id'
    | '/dashboard/kyc-session/$id'
    | '/dashboard/manage-admins/$adminId'
    | '/dashboard/transaction/$id'
    | '/dashboard/treasury/$sweepId'
    | '/dashboard/treasury/wallets'
    | '/dashboard/user/$userId'
    | '/dashboard/coin-management/'
    | '/dashboard/disputes/'
    | '/dashboard/kyc-sessions/'
    | '/dashboard/transactions/'
    | '/dashboard/treasury/'
    | '/dashboard/users/'
    | '/dashboard/disputes/edit/$id'
    | '/dashboard/users/transaction-history/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DashboardAuditTrailsRoute: typeof DashboardAuditTrailsRoute
  DashboardKycTierLimitsRoute: typeof DashboardKycTierLimitsRoute
  DashboardManageAdminsRoute: typeof DashboardManageAdminsRouteWithChildren
  DashboardManageFiatRoute: typeof DashboardManageFiatRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardSupportedCurrenciesRoute: typeof DashboardSupportedCurrenciesRoute
  DashboardTestimonialsRoute: typeof DashboardTestimonialsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCoinManagementCoinIdRoute: typeof DashboardCoinManagementCoinIdRoute
  DashboardCoinManagementAddCoinRoute: typeof DashboardCoinManagementAddCoinRoute
  DashboardCustodialWalletWalletAddressRoute: typeof DashboardCustodialWalletWalletAddressRoute
  DashboardDisputeIdRoute: typeof DashboardDisputeIdRoute
  DashboardKycSessionIdRoute: typeof DashboardKycSessionIdRoute
  DashboardTransactionIdRoute: typeof DashboardTransactionIdRoute
  DashboardTreasurySweepIdRoute: typeof DashboardTreasurySweepIdRoute
  DashboardTreasuryWalletsRoute: typeof DashboardTreasuryWalletsRoute
  DashboardUserUserIdRoute: typeof DashboardUserUserIdRoute
  DashboardCoinManagementIndexRoute: typeof DashboardCoinManagementIndexRoute
  DashboardDisputesIndexRoute: typeof DashboardDisputesIndexRoute
  DashboardKycSessionsIndexRoute: typeof DashboardKycSessionsIndexRoute
  DashboardTransactionsIndexRoute: typeof DashboardTransactionsIndexRoute
  DashboardTreasuryIndexRoute: typeof DashboardTreasuryIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardDisputesEditIdRoute: typeof DashboardDisputesEditIdRoute
  DashboardUsersTransactionHistoryUserIdRoute: typeof DashboardUsersTransactionHistoryUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/testimonials': {
      id: '/dashboard/testimonials'
      path: '/dashboard/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof DashboardTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/supported-currencies': {
      id: '/dashboard/supported-currencies'
      path: '/dashboard/supported-currencies'
      fullPath: '/dashboard/supported-currencies'
      preLoaderRoute: typeof DashboardSupportedCurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manage-fiat': {
      id: '/dashboard/manage-fiat'
      path: '/dashboard/manage-fiat'
      fullPath: '/dashboard/manage-fiat'
      preLoaderRoute: typeof DashboardManageFiatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manage-admins': {
      id: '/dashboard/manage-admins'
      path: '/dashboard/manage-admins'
      fullPath: '/dashboard/manage-admins'
      preLoaderRoute: typeof DashboardManageAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/kyc-tier-limits': {
      id: '/dashboard/kyc-tier-limits'
      path: '/dashboard/kyc-tier-limits'
      fullPath: '/dashboard/kyc-tier-limits'
      preLoaderRoute: typeof DashboardKycTierLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/audit-trails': {
      id: '/dashboard/audit-trails'
      path: '/dashboard/audit-trails'
      fullPath: '/dashboard/audit-trails'
      preLoaderRoute: typeof DashboardAuditTrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/treasury/': {
      id: '/dashboard/treasury/'
      path: '/dashboard/treasury'
      fullPath: '/dashboard/treasury/'
      preLoaderRoute: typeof DashboardTreasuryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transactions/': {
      id: '/dashboard/transactions/'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions/'
      preLoaderRoute: typeof DashboardTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/kyc-sessions/': {
      id: '/dashboard/kyc-sessions/'
      path: '/dashboard/kyc-sessions'
      fullPath: '/dashboard/kyc-sessions/'
      preLoaderRoute: typeof DashboardKycSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/disputes/': {
      id: '/dashboard/disputes/'
      path: '/dashboard/disputes'
      fullPath: '/dashboard/disputes/'
      preLoaderRoute: typeof DashboardDisputesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/coin-management/': {
      id: '/dashboard/coin-management/'
      path: '/dashboard/coin-management'
      fullPath: '/dashboard/coin-management/'
      preLoaderRoute: typeof DashboardCoinManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user/$userId': {
      id: '/dashboard/user/$userId'
      path: '/dashboard/user/$userId'
      fullPath: '/dashboard/user/$userId'
      preLoaderRoute: typeof DashboardUserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/treasury/wallets': {
      id: '/dashboard/treasury/wallets'
      path: '/dashboard/treasury/wallets'
      fullPath: '/dashboard/treasury/wallets'
      preLoaderRoute: typeof DashboardTreasuryWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/treasury/$sweepId': {
      id: '/dashboard/treasury/$sweepId'
      path: '/dashboard/treasury/$sweepId'
      fullPath: '/dashboard/treasury/$sweepId'
      preLoaderRoute: typeof DashboardTreasurySweepIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transaction/$id': {
      id: '/dashboard/transaction/$id'
      path: '/dashboard/transaction/$id'
      fullPath: '/dashboard/transaction/$id'
      preLoaderRoute: typeof DashboardTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manage-admins/$adminId': {
      id: '/dashboard/manage-admins/$adminId'
      path: '/$adminId'
      fullPath: '/dashboard/manage-admins/$adminId'
      preLoaderRoute: typeof DashboardManageAdminsAdminIdRouteImport
      parentRoute: typeof DashboardManageAdminsRoute
    }
    '/dashboard/kyc-session/$id': {
      id: '/dashboard/kyc-session/$id'
      path: '/dashboard/kyc-session/$id'
      fullPath: '/dashboard/kyc-session/$id'
      preLoaderRoute: typeof DashboardKycSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/dispute/$id': {
      id: '/dashboard/dispute/$id'
      path: '/dashboard/dispute/$id'
      fullPath: '/dashboard/dispute/$id'
      preLoaderRoute: typeof DashboardDisputeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/custodial-wallet/$walletAddress': {
      id: '/dashboard/custodial-wallet/$walletAddress'
      path: '/dashboard/custodial-wallet/$walletAddress'
      fullPath: '/dashboard/custodial-wallet/$walletAddress'
      preLoaderRoute: typeof DashboardCustodialWalletWalletAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/coin-management/add-coin': {
      id: '/dashboard/coin-management/add-coin'
      path: '/dashboard/coin-management/add-coin'
      fullPath: '/dashboard/coin-management/add-coin'
      preLoaderRoute: typeof DashboardCoinManagementAddCoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/coin-management/$coinId': {
      id: '/dashboard/coin-management/$coinId'
      path: '/dashboard/coin-management/$coinId'
      fullPath: '/dashboard/coin-management/$coinId'
      preLoaderRoute: typeof DashboardCoinManagementCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users/transaction-history/$userId': {
      id: '/dashboard/users/transaction-history/$userId'
      path: '/dashboard/users/transaction-history/$userId'
      fullPath: '/dashboard/users/transaction-history/$userId'
      preLoaderRoute: typeof DashboardUsersTransactionHistoryUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/disputes/edit/$id': {
      id: '/dashboard/disputes/edit/$id'
      path: '/dashboard/disputes/edit/$id'
      fullPath: '/dashboard/disputes/edit/$id'
      preLoaderRoute: typeof DashboardDisputesEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardManageAdminsRouteChildren {
  DashboardManageAdminsAdminIdRoute: typeof DashboardManageAdminsAdminIdRoute
}

const DashboardManageAdminsRouteChildren: DashboardManageAdminsRouteChildren = {
  DashboardManageAdminsAdminIdRoute: DashboardManageAdminsAdminIdRoute,
}

const DashboardManageAdminsRouteWithChildren =
  DashboardManageAdminsRoute._addFileChildren(
    DashboardManageAdminsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DashboardAuditTrailsRoute: DashboardAuditTrailsRoute,
  DashboardKycTierLimitsRoute: DashboardKycTierLimitsRoute,
  DashboardManageAdminsRoute: DashboardManageAdminsRouteWithChildren,
  DashboardManageFiatRoute: DashboardManageFiatRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardSupportedCurrenciesRoute: DashboardSupportedCurrenciesRoute,
  DashboardTestimonialsRoute: DashboardTestimonialsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCoinManagementCoinIdRoute: DashboardCoinManagementCoinIdRoute,
  DashboardCoinManagementAddCoinRoute: DashboardCoinManagementAddCoinRoute,
  DashboardCustodialWalletWalletAddressRoute:
    DashboardCustodialWalletWalletAddressRoute,
  DashboardDisputeIdRoute: DashboardDisputeIdRoute,
  DashboardKycSessionIdRoute: DashboardKycSessionIdRoute,
  DashboardTransactionIdRoute: DashboardTransactionIdRoute,
  DashboardTreasurySweepIdRoute: DashboardTreasurySweepIdRoute,
  DashboardTreasuryWalletsRoute: DashboardTreasuryWalletsRoute,
  DashboardUserUserIdRoute: DashboardUserUserIdRoute,
  DashboardCoinManagementIndexRoute: DashboardCoinManagementIndexRoute,
  DashboardDisputesIndexRoute: DashboardDisputesIndexRoute,
  DashboardKycSessionsIndexRoute: DashboardKycSessionsIndexRoute,
  DashboardTransactionsIndexRoute: DashboardTransactionsIndexRoute,
  DashboardTreasuryIndexRoute: DashboardTreasuryIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardDisputesEditIdRoute: DashboardDisputesEditIdRoute,
  DashboardUsersTransactionHistoryUserIdRoute:
    DashboardUsersTransactionHistoryUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
